import type { Metadata } from "next";
import { PageHeader } from "@/components/page-header";
import { listPublicFaq } from "@/lib/db/repository";
export const metadata:Metadata={title:"FAQ",description:"Pertanyaan umum tentang layanan, pesanan, pembayaran, dan kebijakan WangStore.",alternates:{canonical:"/faq"}};
export const dynamic="force-dynamic";
const defaults=[
  {id:"platform",category:"Layanan",question:"Apa peran WangStore?",answer:"WangStore menjual dan mengelola hubungan pelanggan untuk layanan hosting. Aplikasi tidak menjalankan server Minecraft, VPS, virtualisasi, atau jaringan pelanggan."},
  {id:"tier",category:"Layanan",question:"Apa perbedaan tier Low, Medium, dan High?",answer:"Low memakai konfigurasi khusus berbasis Intel Xeon E5-2690 v4. Medium memakai paket yang ketersediaannya dikendalikan melalui katalog. High memakai paket tetap berbasis AMD Ryzen 9 9950X."},
  {id:"estimate",category:"Layanan",question:"Apakah estimasi perancang dijamin?",answer:"Tidak. Seluruh angka diberi label Estimasi dan bukan SLA atau jaminan performa."},
  {id:"price",category:"Pemesanan",question:"Mengapa harga dihitung ulang?",answer:"Untuk mencegah manipulasi, server mengabaikan harga dari peramban dan menghitung total menggunakan mesin harga yang sama."},
  {id:"medium",category:"Pemesanan",question:"Kapan Medium dapat dipesan?",answer:"Medium dapat dipesan hanya saat produk dan paket pilihan berstatus Tersedia. Ketika belum tersedia atau dalam pemeliharaan, tindakan pemesanan dinonaktifkan dan API menjawab HTTP 409."},
  {id:"order",category:"Pemesanan",question:"Apa yang terjadi setelah pesanan dibuat?",answer:"Pesanan disimpan dengan status menunggu dan WhatsApp dibuka untuk melanjutkan konsultasi atau memperoleh instruksi pembayaran. Pesanan bukan bukti pembayaran."},
  {id:"final",category:"Kebijakan",question:"Apakah pembelian dapat dibatalkan karena berubah pikiran?",answer:"Tidak. Pembelian bersifat final. Pastikan spesifikasi, paket, dan jenis layanan telah benar sebelum pembayaran."},
  {id:"compensation",category:"Kebijakan",question:"Kapan kompensasi diberikan?",answer:"Jika kesalahan terbukti berasal dari WangStore, bentuk kompensasi bawaan berupa kredit layanan. Pengembalian dana tunai hanya dipertimbangkan bila layanan sama sekali tidak dapat disediakan."},
  {id:"ddos",category:"Kebijakan",question:"Bagaimana perlindungan DDoS?",answer:"Kemampuan perlindungan bergantung pada penyedia jaringan dan tidak dijanjikan tanpa batas."}
];
export default async function FaqPage(){const items=[...defaults,...await listPublicFaq()];const categories=[...new Set(items.map(item=>item.category))];const faqJson={"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))};return <><PageHeader eyebrow="FAQ" title="Jawaban sebelum Anda memesan." description="Informasi faktual mengenai platform, cara pemesanan, harga, performa, dan kebijakan pembelian."/><div className="container-page section-space"><div className="mx-auto max-w-3xl space-y-12">{categories.map(category=><section key={category}><h2 className="heading-2">{category}</h2><div className="mt-5 divide-y border-y">{items.filter(item=>item.category===category).map(item=><details className="py-5" key={item.id}><summary className="cursor-pointer list-none font-medium">{item.question}</summary><p className="mt-3 text-sm leading-6 text-secondary">{item.answer}</p></details>)}</div></section>)}</div></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqJson).replaceAll("<","\\u003c")}}/></>}
