import type { Metadata } from "next";
import { Activity,Clock3 } from "lucide-react";
import { Badge,Card,EmptyState } from "@/components/ui";
import { PageHeader } from "@/components/page-header";
import { formatDate, formatStatus } from "@/lib/utils";
import { getSetting,listPublicIncidents } from "@/lib/db/repository";
export const metadata:Metadata={title:"Status Layanan",description:"Status platform, pemeliharaan, dan insiden WangStore.",alternates:{canonical:"/status"}};
export const dynamic="force-dynamic";
export default async function StatusPage(){const[maintenanceValue,title,message,incidents]=await Promise.all([getSetting("maintenance_enabled"),getSetting("maintenance_title"),getSetting("maintenance_message"),listPublicIncidents()]);const maintenance=maintenanceValue==="true";return <><meta httpEquiv="refresh" content="60"/><PageHeader eyebrow="Status" title="Status platform dan layanan." description="Halaman diperbarui paling lambat setiap 60 detik. Data pemantauan hanya ditampilkan jika sumber pemantauan telah dikonfigurasi."/><div className="container-page section-space"><Card className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-muted"><Activity className="h-5 w-5"/></span><div><h2 className="font-semibold">Platform WangStore</h2><p className="mt-1 text-sm text-secondary">Katalog, akun, pesanan, dan portal</p></div></div><Badge tone={maintenance?"warning":"success"}>{maintenance?"Pemeliharaan":"Tersedia"}</Badge></Card>{maintenance&&<Card className="mt-4"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4"/><h2 className="font-semibold">{title}</h2></div><p className="mt-3 text-sm leading-6 text-secondary">{message}</p></Card>}<div className="mt-10 grid gap-8 md:grid-cols-2"><section><h2 className="heading-2">Ketersediaan & layanan</h2><div className="mt-5"><EmptyState title="Pemantauan belum dikonfigurasi" description="Belum ada sumber pemantauan terverifikasi. WangStore tidak menampilkan persentase ketersediaan atau status komponen rekaan."/></div></section><section><h2 className="heading-2">Riwayat insiden</h2>{incidents.length===0?<div className="mt-5"><EmptyState title="Belum ada insiden tercatat" description="Linimasa insiden akan muncul setelah pengelola memublikasikan informasi insiden."/></div>:<div className="mt-5 space-y-3">{incidents.map(item=><Card key={item.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{item.title}</h3><Badge tone={item.status==="resolved"?"success":"warning"}>{formatStatus(item.status)}</Badge></div><p className="mt-2 text-xs text-subtle">Dampak {formatStatus(item.impact).toLowerCase()} · {formatDate(item.startedAt)}</p><p className="mt-3 text-sm leading-6 text-secondary">{item.message}</p></Card>)}</div>}</section></div></div></>}
