import type { Metadata } from "next";
import Link from "next/link";
import { Mail, MessageCircle, Ticket } from "lucide-react";
import { ContactForm } from "@/components/contact-form";
import { PageHeader } from "@/components/page-header";
import { Alert, Card, linkButton } from "@/components/ui";
import { getSessionUser } from "@/lib/auth";
import { getSetting } from "@/lib/db/repository";
import { normalizeWhatsappNumber } from "@/lib/whatsapp";
export const metadata:Metadata={title:"Kontak",description:"Hubungi WangStore melalui tiket, WhatsApp, Discord, atau email yang dikonfigurasi.",alternates:{canonical:"/contact"}};
export const dynamic="force-dynamic";
export default async function ContactPage(){const [user,wa,email,discord]=await Promise.all([getSessionUser(),getSetting("whatsapp_number"),getSetting("contact_email"),getSetting("discord_url")]);return <><PageHeader eyebrow="Kontak" title="Sampaikan pertanyaan melalui kanal yang tepat." description="Gunakan tiket untuk pertanyaan yang perlu dilacak. Kanal eksternal hanya ditampilkan jika telah dikonfigurasi."/><div className="container-page section-space"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><div className="space-y-4"><Card><Ticket className="h-5 w-5"/><h2 className="heading-3 mt-5">Tiket</h2><p className="mt-2 text-sm leading-6 text-secondary">Formulir di samping mencatat pesan sebagai tiket dengan nomor referensi.</p></Card>{wa?<Card><MessageCircle className="h-5 w-5"/><h2 className="heading-3 mt-5">WhatsApp</h2><p className="mt-2 text-sm text-secondary">Konsultasi pra-pembelian melalui nomor resmi yang dikonfigurasi.</p><a className={`${linkButton("secondary","sm")} mt-4`} href={`https://wa.me/${normalizeWhatsappNumber(wa)}`} target="_blank" rel="noreferrer">Buka WhatsApp</a></Card>:<Alert title="WhatsApp belum dikonfigurasi">Gunakan tiket hingga nomor resmi ditambahkan oleh pengelola.</Alert>}{email&&<Card><Mail className="h-5 w-5"/><h2 className="heading-3 mt-5">Email</h2><a className="mt-3 block text-sm font-medium underline" href={`mailto:${email}`}>{email}</a></Card>}{discord&&<Link className={linkButton("secondary")} href={discord} target="_blank" rel="noreferrer">Buka Discord</Link>}</div><Card className="bg-background"><h2 className="heading-2">Buat tiket kontak</h2><p className="mb-7 mt-2 text-sm text-secondary">Pesan akan disimpan dan dapat ditinjau melalui portal pelanggan bila Anda masuk.</p><ContactForm defaultName={user?.name} defaultEmail={user?.email}/></Card></div></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"ContactPage",name:"Kontak WangStore",url:`${process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000"}/contact`}).replaceAll("<","\\u003c")}}/></>}
