import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Badge, Breadcrumb } from "@/components/ui";
import { getContent, listContent } from "@/lib/db/repository";
import { formatDate, readingTime } from "@/lib/utils";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=await getContent("blog",(await params).slug);if(!item)return{title:"Artikel tidak ditemukan"};return{title:item.seoTitle,description:item.seoDescription,alternates:{canonical:`/blog/${item.slug}`},openGraph:{type:"article",title:item.seoTitle,description:item.seoDescription,publishedTime:item.publishedAt??undefined,authors:[item.author],tags:item.tags}}}
export default async function BlogDetail({params}:{params:Promise<{slug:string}>}){const item=await getContent("blog",(await params).slug);if(!item)notFound();const related=(await listContent("blog")).filter(row=>row.id!==item.id&&(row.category===item.category||row.tags.some(tag=>item.tags.includes(tag)))).slice(0,3);const json={"@context":"https://schema.org","@type":"BlogPosting",headline:item.title,description:item.excerpt,datePublished:item.publishedAt,dateModified:item.updatedAt,author:{"@type":"Person",name:item.author}};return <div className="container-page py-10 sm:py-16"><Breadcrumb items={[{label:"Beranda",href:"/"},{label:"Blog",href:"/blog"},{label:item.title}]}/><article className="mx-auto mt-10 max-w-3xl"><Badge>{item.category}</Badge><h1 className="heading-1 mt-5">{item.title}</h1><p className="mt-5 text-lg leading-8 text-secondary">{item.excerpt}</p><p className="mt-5 text-sm text-subtle">{item.publishedAt?formatDate(item.publishedAt):""} · {item.author} · {readingTime(item.content)} menit baca</p><div className="prose-wang mt-10 border-t pt-6"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.content}</ReactMarkdown></div></article>{related.length>0&&<section className="mx-auto mt-14 max-w-3xl border-t pt-8"><h2 className="heading-2">Artikel terkait</h2><ul className="mt-4 space-y-3">{related.map(row=><li key={row.id}><a className="font-medium underline underline-offset-4" href={`/blog/${row.slug}`}>{row.title}</a></li>)}</ul></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(json).replaceAll("<","\\u003c")}}/></div>}
