import type { Metadata } from "next";
import Link from "next/link";
import { Server } from "lucide-react";
import { Badge, Card, EmptyState, linkButton } from "@/components/ui";
import { PageHeader } from "@/components/page-header";
import { listVpsLocations, listVpsPackages } from "@/lib/db/repository";
import { formatRupiah } from "@/lib/pricing";
import { formatStatus } from "@/lib/utils";
export const metadata:Metadata={title:"Paket VPS",description:"Katalog paket VPS WangStore yang bersumber dari database.",alternates:{canonical:"/vps"}};
export const dynamic="force-dynamic";
export default async function VpsPage(){const [packages,locations]=await Promise.all([listVpsPackages(),listVpsLocations()]);const map=new Map(locations.map(item=>[item.id,item]));return <><PageHeader eyebrow="VPS" title="Paket VPS dari katalog yang dikelola." description="Spesifikasi, lokasi, harga, status, dan ketentuan perpanjangan ditampilkan langsung dari data paket aktif."/><div className="container-page section-space">{packages.length===0?<EmptyState title="Belum ada paket VPS tersedia" description="Pengelola belum memublikasikan paket VPS. WangStore tidak menampilkan spesifikasi, lokasi, stok, atau harga yang belum dikonfigurasi." action={<Link className={linkButton("secondary")} href="/contact">Tanyakan ketersediaan</Link>}/>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{packages.map(item=><Card className="flex flex-col" key={item.id}><div className="flex items-center justify-between"><Server className="h-5 w-5"/><Badge tone={item.status==="available"?"success":item.status==="sold_out"?"error":"warning"}>{formatStatus(item.status)}</Badge></div><h2 className="heading-3 mt-5">{item.name}</h2><p className="mt-2 text-sm leading-6 text-secondary">{item.description}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-subtle">CPU</dt><dd className="mt-1 font-medium">{item.cpu} inti virtual</dd></div><div><dt className="text-subtle">RAM</dt><dd className="mt-1 font-medium">{item.ram} GB</dd></div><div><dt className="text-subtle">Penyimpanan</dt><dd className="mt-1 font-medium">{item.storage} GB</dd></div><div><dt className="text-subtle">Lebar pita</dt><dd className="mt-1 font-medium">{item.bandwidth}</dd></div><div><dt className="text-subtle">IPv4</dt><dd className="mt-1 font-medium">{item.ipv4Available?"Tersedia":"Tidak termasuk"}</dd></div><div><dt className="text-subtle">Lokasi</dt><dd className="mt-1 font-medium">{map.get(item.locationId)?.name??"Informasi diperbarui"}</dd></div></dl><div className="mt-6 border-t pt-5"><p className="text-xl font-semibold">{formatRupiah(item.price)}<span className="text-xs font-normal text-subtle">/{item.billingPeriod==="monthly"?"bulan":item.billingPeriod==="quarterly"?"3 bulan":"tahun"}</span></p><p className="mt-2 text-xs text-subtle">{item.renewable?"Dapat diperpanjang":"Tidak dapat diperpanjang"}</p></div>{item.status==="available"?<Link href="/contact" className={`${linkButton("primary")} mt-5`}>Konsultasikan Paket</Link>:<span className="mt-5 inline-flex min-h-10 items-center justify-center rounded-xl border px-4 py-2 text-sm font-medium text-subtle opacity-60" aria-disabled="true">Paket belum dapat dipesan</span>}</Card>)}</div>}</div></>}
