import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", size = "md", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; size?: "sm" | "md" | "lg" }) {
  return <button className={cn("inline-flex items-center justify-center gap-2 rounded-xl font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-45", variant === "primary" && "bg-primary text-background hover:opacity-85", variant === "secondary" && "border bg-background text-primary hover:bg-surface", variant === "ghost" && "text-secondary hover:bg-surface hover:text-primary", variant === "danger" && "bg-red-600 text-white hover:bg-red-700", size === "sm" && "min-h-9 px-3 text-sm", size === "md" && "min-h-11 px-4 text-sm", size === "lg" && "min-h-12 px-5 text-base", className)} {...props} />;
}
export function linkButton(variant: "primary" | "secondary" | "ghost" = "primary", size: "sm" | "md" | "lg" = "md"): string {
  return cn("inline-flex items-center justify-center gap-2 rounded-xl font-medium transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2", variant === "primary" && "bg-primary text-background hover:opacity-85", variant === "secondary" && "border bg-background text-primary hover:bg-surface", variant === "ghost" && "text-secondary hover:bg-surface hover:text-primary", size === "sm" && "min-h-9 px-3 text-sm", size === "md" && "min-h-11 px-4 text-sm", size === "lg" && "min-h-12 px-5 text-base");
}
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("input-base", className)} {...props} />; }
export function Textarea({ className, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("input-base min-h-28 resize-y py-3", className)} {...props} />; }
export function Select({ className, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn("input-base", className)} {...props} />; }
export function Checkbox({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input type="checkbox" className={cn("h-4 w-4 rounded border accent-current", className)} {...props} />; }
export function Radio({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input type="radio" className={cn("h-4 w-4 accent-current", className)} {...props} />; }
export function Switch({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="inline-flex cursor-pointer items-center gap-3"><input type="checkbox" role="switch" className="peer sr-only" {...props} /><span className="relative h-6 w-11 rounded-full bg-muted after:absolute after:left-1 after:top-1 after:h-4 after:w-4 after:rounded-full after:bg-secondary after:transition-transform peer-checked:bg-primary peer-checked:after:translate-x-5 peer-checked:after:bg-background"/><span className="text-sm">{label}</span></label>; }
export function Slider({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input type="range" className={cn("h-2 w-full cursor-pointer accent-current", className)} {...props} />; }
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-2xl border bg-surface p-5 sm:p-6", className)} {...props} />; }
export function Badge({ children, tone = "neutral", className }: { children: React.ReactNode; tone?: "neutral" | "success" | "warning" | "error" | "info"; className?: string }) { return <span className={cn("inline-flex rounded-full border px-2.5 py-1 text-xs font-medium", tone === "neutral" && "bg-muted text-secondary", tone === "success" && "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-300", tone === "warning" && "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-300", tone === "error" && "border-red-200 bg-red-50 text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-300", tone === "info" && "border-blue-200 bg-blue-50 text-blue-800 dark:border-blue-900 dark:bg-blue-950 dark:text-blue-300", className)}>{children}</span>; }
export function Alert({ title, children, tone = "info" }: { title: string; children: React.ReactNode; tone?: "info" | "warning" | "error" | "success" }) { return <div role={tone === "error" ? "alert" : "status"} className={cn("rounded-xl border p-4 text-sm", tone === "warning" && "border-amber-200 bg-amber-50 text-amber-950 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200", tone === "error" && "border-red-200 bg-red-50 text-red-950 dark:border-red-900 dark:bg-red-950 dark:text-red-200", tone === "success" && "border-emerald-200 bg-emerald-50 text-emerald-950 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-200", tone === "info" && "bg-surface text-primary")}><p className="font-semibold">{title}</p><div className="mt-1 leading-6 opacity-85">{children}</div></div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="rounded-2xl border border-dashed p-8 text-center"><h2 className="heading-3">{title}</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-secondary">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function LoadingState({ label = "Memuat data" }: { label?: string }) { return <div role="status" className="flex items-center gap-3 py-8 text-sm text-secondary"><span className="h-4 w-4 animate-spin rounded-full border-2 border-muted border-t-primary"/><span>{label}…</span></div>; }
export function ErrorState({ message }: { message: string }) { return <Alert title="Terjadi kendala" tone="error">{message}</Alert>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden="true" className={cn("animate-pulse rounded-lg bg-muted", className)} />; }
export function StatCard({ label, value, detail }: { label: string; value: string; detail?: string }) { return <Card><p className="text-sm text-secondary">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p>{detail && <p className="mt-1 text-xs text-subtle">{detail}</p>}</Card>; }
export function Breadcrumb({ items }: { items: Array<{ label: string; href?: string }> }) { return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap items-center gap-2 text-sm text-secondary">{items.map((item, index) => <li className="flex items-center gap-2" key={`${item.label}-${index}`}>{index > 0 && <span aria-hidden="true">/</span>}{item.href ? <a href={item.href} className="hover:text-primary">{item.label}</a> : <span aria-current="page">{item.label}</span>}</li>)}</ol></nav>; }
export function Pagination({ page, totalPages, basePath }: { page: number; totalPages: number; basePath: string }) { return <nav aria-label="Paginasi" className="flex items-center justify-between"><a aria-disabled={page <= 1} className={cn(linkButton("secondary", "sm"), page <= 1 && "pointer-events-none opacity-45")} href={`${basePath}?page=${Math.max(1, page - 1)}`}>Sebelumnya</a><span className="text-sm text-secondary">Halaman {page} dari {totalPages}</span><a aria-disabled={page >= totalPages} className={cn(linkButton("secondary", "sm"), page >= totalPages && "pointer-events-none opacity-45")} href={`${basePath}?page=${Math.min(totalPages, page + 1)}`}>Berikutnya</a></nav>; }
export function Tabs({ items, active }: { items: Array<{ label: string; href: string }>; active: string }) { return <nav className="flex gap-1 overflow-x-auto rounded-xl bg-muted p-1" aria-label="Tab">{items.map((item) => <a key={item.href} href={item.href} aria-current={active === item.href ? "page" : undefined} className={cn("whitespace-nowrap rounded-lg px-3 py-2 text-sm", active === item.href ? "bg-background font-medium text-primary shadow-sm" : "text-secondary hover:text-primary")}>{item.label}</a>)}</nav>; }
export function Tooltip({ label, children }: { label: string; children: React.ReactNode }) { return <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 z-20 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-primary px-2 py-1 text-xs text-background group-hover:block group-focus-within:block">{label}</span></span>; }
export function Table({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[640px] text-left text-sm">{children}</table></div>; }
export function OrderSummary({ children }: { children: React.ReactNode }) { return <aside className="rounded-2xl border bg-surface p-5 sm:p-6"><h2 className="heading-3">Ringkasan Pesanan</h2><div className="mt-5 space-y-3 text-sm">{children}</div></aside>; }
export const PriceCard = Card;
export const PackageCard = Card;
