import { z } from "zod";
import type { Role } from "@/types";
const slug=z.string().trim().min(2).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,"Slug hanya boleh memuat huruf kecil, angka, dan tanda hubung.");
const status=z.enum(["draft","published"]);
const contentBase={slug,title:z.string().trim().min(3).max(200),excerpt:z.string().trim().min(10).max(500),content:z.string().trim().min(20).max(100000),category:z.string().trim().min(2).max(80),tags:z.array(z.string().trim().min(1).max(50)).max(20),author:z.string().trim().min(2).max(100),status,publishedAt:z.string().datetime().nullable(),seoTitle:z.string().trim().min(3).max(200),seoDescription:z.string().trim().min(10).max(320)};
export interface ResourceDefinition { table:string;identityField:string;allowedFields:readonly string[];schema:z.ZodObject<z.ZodRawShape>;minimumRole:Exclude<Role,"customer">;readOnly?:boolean;createDisabled?:boolean;deleteDisabled?:boolean }
const define=(definition:ResourceDefinition)=>definition;
export const resourceMap={
  pages:define({table:"pages",identityField:"slug",allowedFields:["slug","title","content","status","seoTitle","seoDescription"],schema:z.object({slug,title:z.string().min(3).max(200),content:z.string().min(20).max(100000),status,seoTitle:z.string().min(3).max(200),seoDescription:z.string().min(10).max(320)}).strict(),minimumRole:"admin"}),
  faq:define({table:"faq_items",identityField:"id",allowedFields:["question","answer","category","sortOrder","published"],schema:z.object({question:z.string().min(5).max(300),answer:z.string().min(10).max(4000),category:z.string().min(2).max(80),sortOrder:z.number().int().min(0).max(10000),published:z.boolean()}).strict(),minimumRole:"admin"}),
  testimonials:define({table:"testimonials",identityField:"id",allowedFields:["customerName","quote","source","verified","published"],schema:z.object({customerName:z.string().min(2).max(100),quote:z.string().min(10).max(2000),source:z.string().min(2).max(100),verified:z.boolean(),published:z.boolean()}).strict(),minimumRole:"owner"}),
  blog:define({table:"blog_posts",identityField:"slug",allowedFields:Object.keys(contentBase),schema:z.object(contentBase).strict(),minimumRole:"admin"}),
  knowledgeBase:define({table:"knowledge_articles",identityField:"slug",allowedFields:Object.keys(contentBase),schema:z.object(contentBase).strict(),minimumRole:"admin"}),
  legal:define({table:"legal_documents",identityField:"slug",allowedFields:["slug","title","content","version","status","seoTitle","seoDescription"],schema:z.object({slug,title:z.string().min(3).max(200),content:z.string().min(20).max(100000),version:z.string().min(1).max(30),status,seoTitle:z.string().min(3).max(200),seoDescription:z.string().min(10).max(320)}).strict(),minimumRole:"owner"}),
  announcements:define({table:"announcements",identityField:"id",allowedFields:["title","message","startsAt","endsAt","active"],schema:z.object({title:z.string().min(3).max(200),message:z.string().min(5).max(2000),startsAt:z.string().datetime(),endsAt:z.string().datetime().nullable(),active:z.boolean()}).strict(),minimumRole:"admin"}),
  incidents:define({table:"incidents",identityField:"id",allowedFields:["title","status","impact","message","startedAt","resolvedAt","published"],schema:z.object({title:z.string().min(3).max(200),status:z.enum(["investigating","identified","monitoring","resolved"]),impact:z.enum(["none","minor","major","critical"]),message:z.string().min(5).max(4000),startedAt:z.string().datetime(),resolvedAt:z.string().datetime().nullable(),published:z.boolean()}).strict(),minimumRole:"admin"}),
  maintenance:define({table:"app_settings",identityField:"key",allowedFields:["enabled","title","message","estimatedRestoration","allowedPaths"],schema:z.object({enabled:z.boolean(),title:z.string().min(3).max(200),message:z.string().min(5).max(2000),estimatedRestoration:z.string().datetime().nullable(),allowedPaths:z.array(z.string().startsWith("/")).max(30)}).strict(),minimumRole:"admin"}),
  products:define({table:"products",identityField:"slug",allowedFields:["name","slug","description","tier","serviceType","status","visibility","renewable","metadata"],schema:z.object({name:z.string().min(3).max(160),slug,description:z.string().min(10).max(2000),tier:z.enum(["low","medium","high"]).nullable(),serviceType:z.enum(["minecraft","vps","dedicated","panel","other"]),status:z.enum(["available","ongoing","maintenance","inactive"]),visibility:z.boolean(),renewable:z.boolean(),metadata:z.record(z.string(),z.union([z.string(),z.number(),z.boolean(),z.null()]))}).strict(),minimumRole:"admin"}),
  coupons:define({table:"coupons",identityField:"code",allowedFields:["code","discountType","discountValue","minimumOrder","expiresAt","maximumUsage","usagePerCustomer","applicableTier","active"],schema:z.object({code:z.string().trim().toUpperCase().min(2).max(40).regex(/^[A-Z0-9_-]+$/),discountType:z.enum(["percentage","fixed"]),discountValue:z.number().positive(),minimumOrder:z.number().int().nonnegative(),expiresAt:z.string().datetime().nullable(),maximumUsage:z.number().int().positive().nullable(),usagePerCustomer:z.number().int().positive(),applicableTier:z.enum(["low","medium","high"]).nullable(),active:z.boolean()}).strict(),minimumRole:"admin"}),
  packages:define({table:"packages",identityField:"id",allowedFields:["id","tier","name","cpu","ram","storage","price","status","popular"],schema:z.object({id:slug,tier:z.literal("medium"),name:z.string().min(3).max(160),cpu:z.number().int().positive().max(128),ram:z.number().int().positive().max(2048),storage:z.number().int().positive().max(160),price:z.number().int().positive(),status:z.enum(["available","ongoing","maintenance","inactive"]),popular:z.boolean()}).strict(),minimumRole:"admin"}),
  vpsLocations:define({table:"vps_locations",identityField:"id",allowedFields:["name","country","city","status"],schema:z.object({name:z.string().min(2).max(120),country:z.string().min(2).max(100),city:z.string().min(2).max(100),status:z.enum(["active","maintenance","inactive"])}).strict(),minimumRole:"admin"}),
  vps:define({table:"vps_packages",identityField:"slug",allowedFields:["name","slug","cpu","ram","storage","bandwidth","ipv4Available","locationId","virtualization","price","billingPeriod","durationDays","renewable","status","visibility","description","features"],schema:z.object({name:z.string().min(3).max(160),slug,cpu:z.number().int().positive().max(128),ram:z.number().int().positive().max(2048),storage:z.number().int().positive().max(100000),bandwidth:z.string().min(1).max(100),ipv4Available:z.boolean(),locationId:z.string().uuid(),virtualization:z.string().min(2).max(80),price:z.number().int().positive(),billingPeriod:z.enum(["monthly","quarterly","yearly"]),durationDays:z.number().int().positive().max(3660),renewable:z.boolean(),status:z.enum(["available","sold_out","maintenance","inactive"]),visibility:z.boolean(),description:z.string().min(10).max(2000),features:z.array(z.string().min(2).max(200)).max(30)}).strict(),minimumRole:"admin"}),
  services:define({table:"service_instances",identityField:"id",allowedFields:["status","renewable","reason"],schema:z.object({status:z.enum(["pending","scheduled","active","suspended","expired","cancelled","terminated"]),renewable:z.boolean(),reason:z.string().min(5).max(500)}).strict(),minimumRole:"admin"}),
  orders:define({table:"orders",identityField:"id",allowedFields:["status","paymentReference","reason"],schema:z.object({status:z.enum(["pending","awaiting_payment","paid","processing","completed","cancelled","expired","refunded"]),paymentReference:z.string().max(160).nullable(),reason:z.string().min(5).max(500)}).strict(),minimumRole:"staff",createDisabled:true,deleteDisabled:true}),
  tickets:define({table:"tickets",identityField:"id",allowedFields:["status","priority"],schema:z.object({status:z.enum(["open","in_progress","resolved","closed"]),priority:z.enum(["low","normal","high","critical"])}).strict(),minimumRole:"staff",createDisabled:true,deleteDisabled:true}),
  customers:define({table:"profiles",identityField:"id",allowedFields:[],schema:z.object({}).strict(),minimumRole:"staff",readOnly:true}),
  settings:define({table:"app_settings",identityField:"key",allowedFields:["key","value"],schema:z.object({key:z.enum(["site_name","site_description","contact_email","whatsapp_number","discord_url","infrastructure_note"]),value:z.string().max(2000)}).strict(),minimumRole:"admin",deleteDisabled:true}),
  audit:define({table:"audit_logs",identityField:"id",allowedFields:[],schema:z.object({}).strict(),minimumRole:"admin",readOnly:true})
} as const;
export type ResourceName=keyof typeof resourceMap;
export function isResourceName(value:string):value is ResourceName{return Object.hasOwn(resourceMap,value)}
