import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Bell, BookOpen, Boxes, MessageCircle, Save, ShoppingBag, Ticket, UserRound } from "lucide-react";
import { ChangePasswordForm, LogoutButton, ProfileForm, RenewalForm } from "@/components/dashboard-actions";
import { Alert, Badge, Card, EmptyState, StatCard, Table, linkButton } from "@/components/ui";
import { getSessionUser } from "@/lib/auth";
import { getProfileContact, getSetting, listNotifications, listOrdersForUser, listSavedConfigurations, listServiceRenewals, listServices, listTickets } from "@/lib/db/repository";
import { effectiveServiceStatus, remainingDuration } from "@/lib/lifecycle";
import { formatRupiah } from "@/lib/pricing";
import { formatDate, formatStatus } from "@/lib/utils";
import { normalizeWhatsappNumber } from "@/lib/whatsapp";
export const metadata:Metadata={title:"Portal Pelanggan",robots:{index:false,follow:false}};export const dynamic="force-dynamic";
const menu=[["ringkasan","Ringkasan",Boxes],["pesanan","Pesanan",ShoppingBag],["layanan","Layanan Saya",Boxes],["konfigurasi","Konfigurasi Tersimpan",Save],["tiket","Tiket",Ticket],["kupon","Kupon",ShoppingBag],["notifikasi","Notifikasi",Bell],["profil","Profil",UserRound],["knowledge","Pusat Pengetahuan",BookOpen],["kontak","WhatsApp & Discord",MessageCircle]] as const;
function statusTone(status:string):"success"|"warning"|"error"|"neutral"{if(["active","paid","completed"].includes(status))return"success";if(["cancelled","terminated","refunded"].includes(status))return"error";if(["pending","scheduled","awaiting_payment","processing"].includes(status))return"warning";return"neutral"}
export default async function DashboardPage(){const user=await getSessionUser();if(!user)redirect("/login?next=/dashboard");if(user.role!=="customer")redirect("/admin");const [orders,services,renewals,configs,tickets,notifications,wa,discord,profile]=await Promise.all([listOrdersForUser(user),listServices(user),listServiceRenewals(user),listSavedConfigurations(user.id),listTickets(user),listNotifications(user.id),getSetting("whatsapp_number"),getSetting("discord_url"),getProfileContact(user.id)]);return <div className="container-page py-8 sm:py-12"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Portal Pelanggan</p><h1 className="heading-1">Halo, {user.name}.</h1><p className="mt-2 text-secondary">Kelola pesanan, layanan, dan dukungan dari satu tempat.</p></div><LogoutButton/></header><div className="mt-8 grid gap-8 lg:grid-cols-[220px_1fr]"><aside><nav className="sticky top-24 space-y-1" aria-label="Menu portal pelanggan">{menu.map(([id,label,Icon])=><a className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-secondary hover:bg-surface hover:text-primary" href={`#${id}`} key={id}><Icon className="h-4 w-4"/>{label}</a>)}</nav></aside><div className="min-w-0 space-y-14"><section id="ringkasan" className="scroll-mt-24"><h2 className="heading-2">Ringkasan</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total pesanan" value={String(orders.length)}/><StatCard label="Layanan aktif" value={String(services.filter(item=>effectiveServiceStatus(item.status,item.activationAt,item.expiresAt)==="active").length)}/><StatCard label="Tiket terbuka" value={String(tickets.filter(item=>!["resolved","closed"].includes(item.status)).length)}/><StatCard label="Notifikasi belum dibaca" value={String(notifications.filter(item=>!item.readAt).length)}/></div></section>
<section id="pesanan" className="scroll-mt-24"><div className="flex items-center justify-between"><h2 className="heading-2">Pesanan</h2><Link className={linkButton("primary","sm")} href="/server-builder">Rancang Server</Link></div><div className="mt-5">{orders.length===0?<EmptyState title="Belum ada pesanan" description="Pesanan resmi yang berhasil dibuat akan muncul di sini."/>:<Table><thead className="bg-muted text-xs text-secondary"><tr><th className="p-3">ID Pesanan</th><th className="p-3">Tanggal</th><th className="p-3">Tier</th><th className="p-3">Konfigurasi</th><th className="p-3">Total</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y">{orders.map(order=><tr key={order.id}><td className="p-3 font-medium">{order.id}</td><td className="p-3 text-secondary">{formatDate(order.createdAt)}</td><td className="p-3 uppercase">{order.tier}</td><td className="p-3">{order.cpu}c / {order.ram}GB / {order.storage}GB</td><td className="p-3">{formatRupiah(order.total)}</td><td className="p-3"><Badge tone={statusTone(order.status)}>{formatStatus(order.status)}</Badge></td></tr>)}</tbody></Table>}</div></section>
<section id="layanan" className="scroll-mt-24"><h2 className="heading-2">Layanan Saya</h2><div className="mt-5 grid gap-4">{services.length===0?<EmptyState title="Belum ada layanan" description="Layanan dibuat setelah pembayaran atau konfirmasi manual, lalu mengikuti waktu aktivasi yang ditetapkan."/>:services.map(service=>{const status=effectiveServiceStatus(service.status,service.activationAt,service.expiresAt);const pendingRenewal=renewals.some(item=>item.serviceId===service.id&&item.status==="pending");return <Card key={service.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-subtle">ID Layanan</p><h3 className="mt-1 font-semibold">{service.id}</h3></div><Badge tone={statusTone(status)}>{formatStatus(status)}</Badge></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-subtle">Aktivasi</dt><dd className="mt-1 font-medium">{formatDate(service.activationAt)}</dd></div><div><dt className="text-subtle">Berakhir</dt><dd className="mt-1 font-medium">{formatDate(service.expiresAt)}</dd></div><div><dt className="text-subtle">Sisa masa</dt><dd className="mt-1 font-medium">{remainingDuration(service.expiresAt)}</dd></div><div><dt className="text-subtle">Harga</dt><dd className="mt-1 font-medium">{formatRupiah(service.price)}</dd></div></dl><p className="mt-4 text-sm text-secondary">Pesanan: {service.orderId} · {service.renewable?"Dapat diperpanjang":"Layanan ini tidak dapat diperpanjang."}</p>{service.renewable&&(pendingRenewal?<Alert title="Perpanjangan menunggu konfirmasi">Selesaikan pembayaran atau hubungi dukungan dengan nomor perpanjangan pada riwayat di bawah.</Alert>:<RenewalForm serviceId={service.id}/>)}</Card>})}</div>{renewals.length>0&&<div className="mt-6"><h3 className="font-semibold">Riwayat perpanjangan</h3><div className="mt-3 space-y-2">{renewals.map(renewal=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-sm" key={renewal.id}><div><p className="font-mono font-medium">{renewal.orderId}</p><p className="mt-1 text-xs text-subtle">Layanan {renewal.serviceId} · {renewal.duration} hari · {formatRupiah(renewal.price)}</p></div><Badge tone={statusTone(renewal.status)}>{formatStatus(renewal.status)}</Badge></div>)}</div></div>}</section>
<section id="konfigurasi" className="scroll-mt-24"><h2 className="heading-2">Konfigurasi Tersimpan</h2><div className="mt-5">{configs.length===0?<EmptyState title="Belum ada konfigurasi tersimpan" description="Gunakan tombol Simpan konfigurasi pada Perancang Server untuk menyimpan pilihan ke akun."/>:<div className="grid gap-3 md:grid-cols-2">{configs.map(item=><Card key={item.id}><h3 className="font-semibold">{item.name}</h3><p className="mt-2 text-sm text-secondary">Tier {item.tier} · {item.cpu} inti · {item.ram} GB RAM · {item.storage} GB</p></Card>)}</div>}</div></section>
<section id="tiket" className="scroll-mt-24"><div className="flex justify-between gap-3"><h2 className="heading-2">Tiket</h2><Link className={linkButton("secondary","sm")} href="/contact">Buat Tiket</Link></div><div className="mt-5">{tickets.length===0?<EmptyState title="Belum ada tiket" description="Pertanyaan yang dikirim melalui formulir kontak saat Anda masuk akan tercatat di sini."/>:<div className="space-y-3">{tickets.map(ticket=><Card key={ticket.id}><div className="flex justify-between"><h3 className="font-semibold">{ticket.subject}</h3><Badge tone={statusTone(ticket.status)}>{formatStatus(ticket.status)}</Badge></div><p className="mt-2 text-sm text-secondary">{ticket.id} · {formatDate(ticket.createdAt)}</p></Card>)}</div>}</div></section>
<section id="kupon" className="scroll-mt-24"><h2 className="heading-2">Kupon</h2><div className="mt-5"><Alert title="Kupon diverifikasi saat digunakan">Masukkan kode pada Perancang Server. Kelayakan, masa berlaku, batas penggunaan, nilai minimum pesanan, dan nilai diskon selalu dihitung oleh server.</Alert></div></section>
<section id="notifikasi" className="scroll-mt-24"><h2 className="heading-2">Notifikasi</h2><div className="mt-5">{notifications.length===0?<EmptyState title="Belum ada notifikasi" description="Pembaruan layanan dan pengingat akan muncul di sini setelah dihasilkan oleh sistem."/>:<div className="space-y-3">{notifications.map(item=><Card key={item.id}><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-secondary">{item.message}</p><p className="mt-3 text-xs text-subtle">{formatDate(item.createdAt)}</p></Card>)}</div>}</div></section>
<section id="profil" className="scroll-mt-24"><h2 className="heading-2">Profil</h2><div className="mt-5 grid max-w-4xl gap-5 md:grid-cols-2"><Card><p className="mb-4 text-sm text-secondary">Email: {user.email} · Terverifikasi</p><ProfileForm name={user.name} whatsapp={profile.whatsapp}/></Card><Card><h3 className="mb-4 font-semibold">Keamanan akun</h3><ChangePasswordForm/></Card></div></section>
<section id="knowledge" className="scroll-mt-24"><h2 className="heading-2">Pusat Pengetahuan</h2><Card className="mt-5"><p className="text-sm leading-6 text-secondary">Temukan panduan Memulai, Pemesanan, Pembayaran, Minecraft, Server, Pemecahan Masalah, Akun, dan Kebijakan.</p><Link className={`${linkButton("secondary","sm")} mt-4`} href="/knowledge-base">Buka Pusat Pengetahuan</Link></Card></section>
<section id="kontak" className="scroll-mt-24"><h2 className="heading-2">WhatsApp & Discord</h2><div className="mt-5 flex flex-wrap gap-3">{wa?<a className={linkButton()} href={`https://wa.me/${normalizeWhatsappNumber(wa)}`} target="_blank" rel="noreferrer">Buka WhatsApp</a>:<Alert title="WhatsApp belum dikonfigurasi">Gunakan tiket untuk menghubungi WangStore.</Alert>}{discord&&<a className={linkButton("secondary")} href={discord} target="_blank" rel="noreferrer">Buka Discord</a>}</div></section></div></div></div>}
